### ISSUE TITLE
Make Search components

### ISSUE THREAD

**Issue by sim0417** [codestates/Phovis-client#103]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Make Search components

### TODO
1. [ ] Search bar component
2. [ ] Loading & empty UI
3. [ ] Content List component

### Estimated time
`3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Urgency: `Middle`
