### ISSUE TITLE
Make a feature of the search page

### ISSUE THREAD

**Issue by sim0417** [codestates/Phovis-client#104]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Make a feature of the search page

### TODO
1. [ ] show search keyword history
2. [ ] show recommend keyword
3. [ ] load new contents use infinite scroll

### Estimated time
`1h`

### Labels
- Estimated time: `E: 1h`
- Group : `client`
- Urgency: `Middle`
