### ISSUE TITLE
Make User page components

### ISSUE THREAD

**Issue by sim0417** [codestates/Phovis-client#106]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Make User Page components

### TODO
1. [ ] user page header component
2. [ ] user contents component
3. [ ] user like component
4. [ ] user bookmark component

### Estimated time
`4h`

### Labels
- Estimated time: `E: 4h`
- Group : `client`
- Urgency: `Middle`
