### ISSUE TITLE
Request user page data from server 

### ISSUE THREAD

**Issue by sim0417** [codestates/Phovis-client#108]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Request user page data from server 

### TODO
1. [ ] make a user contents request
2. [ ] make a change user setting  request
3. [ ] make a change user profile  request

### Estimated time
`1h`

### Labels
- Estimated time: `E: 1h`
- Group : `client`
- Urgency: `Middle`
