### ISSUE TITLE
nextjs with styled-components setup

### ISSUE THREAD

**Issue by seungsang00** [codestates/Phovis-client#7]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: initialize boilerplate about styled-components

### TODO
1. [ ] styled-components setup
2. [ ] global-styles setup
3. [ ] theme setup
4. [ ] withSizes setup
5. [ ] themed-components setup
6. [ ] common styled-components setup

### Estimated time
`3h`
