### ISSUE TITLE
Load main page data

### ISSUE THREAD

**Issue by sim0417** [codestates/Phovis-client#74]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Load main page contents data

### TODO
1. [ ] Get main banner data
2. [ ] Get recommend data
3. [ ] Get Hot spot tag data
4. [ ] Get random content & photo card data
 
### Estimated time
`3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Urgency: `Middle`
