### ISSUE TITLE
Make main page components

### ISSUE THREAD

**Issue by sim0417** [codestates/Phovis-client#75]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: make main page components

### TODO
1. [ ] main header
2. [ ] main recommend container
3. [ ] Hot keyword list viewer
4. [ ] main content gallery

### Labels
- Estimated time: `E: 1h`
- Group : `client`
- Urgency: `Middle`
